# Stuck on startup

11:01:14 [INFO]: GenICam.py:41: Init: GeniCam
11:01:14 [INFO]: GenICam.py:50: Config loaded
11:01:14 [INFO]: GenICam.py:55: Harvester created
11:01:14 [INFO]: GenICam.py:58: ./cti/ximea.gentl.cti
11:01:14 [INFO]: GenICam.py:58: ./cti/ids_u3vgentl.cti
11:01:14 [INFO]: GenICam.py:58: ./cti/VimbaUSBTL.cti
11:01:14 [INFO]: GenICam.py:60: ['./cti/ximea.gentl.cti', './cti/ids_u3vgentl.cti', './cti/VimbaUSBTL.cti']
11:01:23 [INFO]: GenICam.py:62: ctis loaded
11:01:44 [INFO]: GenICam.py:74: (id_='MQ013CG-E2 (38205351)', vendor='XIMEA GmbH.', model='MQ013CG-E2', tl_type='Custom', user_defined_name=None, serial_number='38205351', version='V4.27.11.00')
11:02:10 [INFO]: GenICam.py:74: (id_='1AB22C00DFE5', vendor='Allied Vision', model='1800 U-508c', tl_type='U3V', user_defined_name=None, serial_number='01885', version='14665')
11:02:10 [WARNING]: GenICam.py:79: could not creare Image-Acquirer for (id_='1AB22C00DFE5', vendor='Allied Vision', model='1800 U-508c', tl_type='U3V', user_defined_name=None, serial_number='01885', version='14665')
11:02:10 [INFO]: GenICam.py:74: (id_='DEV_1AB22C00DFE5', vendor='Allied Vision', model='1800 U-508c', tl_type='U3V', user_defined_name=None, serial_number=None, version=None)
11:02:10 [WARNING]: GenICam.py:163: Gain: 0.0 <class 'float'>
11:02:11 [INFO]: GenICam.py:94: changed ImageAcquirer from None to MQ013CG-E2 (38205351)
11:02:11 [WARNING]: GenICam.py:163: Gain: 0.0 <class 'float'>

restarting programms fixes it, bad state?
occures every other startup
seemse to be caused by Allied Vision
